on:
  push:
    branches:
      - master
  pull_request:

name: Tests on Windows
jobs:
  test:
    name: Rust tests
    runs-on: windows-latest
    strategy:
      matrix:
        target: [x86_64-pc-windows-gnu] # Not running `x86_64-pc-windows-msvc` for now

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Use stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: Run cargo tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target ${{ matrix.target }}
